package http

import (
	_ "SocialNetHTTPService/docs" // docs is generated by Swag CLI, you have to import it.
	"SocialNetHTTPService/internal/service"
	"github.com/go-chi/chi"
	httpSwagger "github.com/swaggo/http-swagger"
)

type Handler struct {
	usersService   service.Users
	friendsService service.Friends
}

func NewHandler(usersService service.Users, friendsService service.Friends) *Handler {
	return &Handler{friendsService: friendsService, usersService: usersService}
}

func (h *Handler) Init() *chi.Mux {
	router := GetRouter()
	h.MountRoutes(router)
	router.GetMux().Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8080/swagger/doc.json"), //The url pointing to API definition
	))
	return router.GetMux()
}
